### ISSUE TITLE
'RealNVP' object has no attribute 'module'

### ISSUE THREAD

**Issue by Haow235** [izmailovpavel/flowgmm#8]
When I training the model for image classification, line 83 in file train_semisup_cons.py generates an error, shows "'RealNVP' object has no attribute 'module'". I checked your RealNVP file and didn't find attribute 'module' over there.

**Comment by izmailovpavel** [comment]
Hi @Haow235 the `.module` part is appended because of the use of `torch.nn.DataParallel`. I suspect that the issue you describe happens because you are trying to run on a cpu? We are definitely not handling the error well, but if you are, I would say that realistically you can't run these experiments on cpu.

**Comment by Haow235** [comment]
Hi, thank you for your reply. I do use GPU to train the model, however, I only have one GPU, so I didn't run the torch.nn.DataParallel part of code.  Also, I removed the 'module' from the code, and it runs well

**Comment by izmailovpavel** [comment]
Nice! We actually also used a single GPU for all the experiments, the `torch.nn.DataParallel` works ok even if you have a single GPU :)
